### ISSUE TITLE
I can't store bitmap

### ISSUE THREAD

**Issue by zsndev** [lowlevel-studios/chronos#10]
when i store bitmap, it crashed. So for now , I transfer bitmap to File, then store it. Can you support store bitmap, or just I use storo wrongly?

**Comment by waninkoko** [comment]
@zsndev A bitmap is probably just too much for Storo. The library is more focused in lightweight classes and POJOs.

To cache a bitmap, I would recommend you to directly use the ```disklrucache``` library, which is the same one that Store uses to manage the disk cache.
