### ISSUE TITLE
Always getting hasExpired to true

### ISSUE THREAD

**Issue by Dharmendra10** [lowlevel-studios/chronos#2]
I am trying to save entity into cache and after caching I am checking expiry but it always returns true.

Below is the entity class which I am trying to cache

```
public class ProductWiseOptionTypesEntity implements Serializable{
    @SerializedName("products")
    @Expose
    private List<Product> products = new ArrayList<>();
    public List<Product> getProducts() {
        return products;
    }
    public static class Product {
        @SerializedName("id")
        private int id;
        @SerializedName("name")
        private String name;
        @SerializedName("option_types")
        private List<ProductOptionTypeEntity> optionTypes;
    }
}
```

Below configuration I have used in the application class

```
StoroBuilder.configure(8192)  // maximum size to allocate in bytes
                .setDefaultCacheDirectory(this)
                .initialize();
```

I am using below method to put object into cache
`Storo.put("key", ProductWiseOptionTypesEntityObject).setExpiry(60*60*1000, TimeUnit.MILLISECONDS).execute();`

I am using below method to check expiry
`Boolean expired = Storo.hasExpired("key").execute();`

**Comment by waninkoko** [comment]
Thanks for opening this issue. This is something that I definitively should look into.

I'll reply soon with some news.

**Comment by waninkoko** [comment]
@Dharmendra10 Are you using ProGuard by any chance?

**Comment by Dharmendra10** [comment]
Nope, not using proguard

**Comment by waninkoko** [comment]
I've written a quick sample code that uses the same methods and classes, but I'm not able to reproduce the issue.

Can you send me some code (or a full Android Studio project) where this problem actually happens?
