### ISSUE TITLE
RxJava 2 support

### ISSUE THREAD

**Issue by Zeyad-37** [lowlevel-studios/chronos#9]
Is there any plans for RxJava 2 support ?

**Comment by waninkoko** [comment]
Yes. Adding support for RxJava 2 is in the roadmap and expected to be ready soon.

**Comment by Zeyad-37** [comment]
Any updates here ?
I have the changes ready, but i can not submit a pull request.

**Comment by waninkoko** [comment]
I'm still waiting to have some free time to take a look at RxJava 2.

If you have the necessary changes already made, I would love to get a patch or something to integrate it asap.

**Comment by Zeyad-37** [comment]
The patch that i have, i replace the rxjava gradle provided dependency with rxjava2. And in the BaseMethod class in replaced the Observable with a Flowable. Does this sound good to you ?
Also i removed the observeOn(AndroidSchedulers.mainThread())

**Comment by patrickfdsouza** [comment]
@Zeyad-37 is the commit missing?

**Comment by Zeyad-37** [comment]
@patrickfdsouza yes

**Comment by Zeyad-37** [comment]
dude i guess i will just fork this project and do it my self

**Comment by Zeyad-37** [comment]
https://github.com/Zeyad-37/storo/

**Comment by waninkoko** [comment]
RxJava 2 support is now available (with RxJava 1.x support still included).
